name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
    - uses: actions/download-artifact@v4
      with:
        name: shycc
    - name: Display structure of downloaded files
      run: ls -R
          
